### ISSUE TITLE
как пользоваться

### ISSUE THREAD

**Issue by maltsevvv** [dbutrimov/flexget-plugins#1]
Здравствуйте, подскажите как должен выглядет конфиг? как установить плагины
```
tasks:
## LOSTFILM.TV
  lostfilm.tv:
    template:
      - transmission
      - notifycation
      - tvshows
    manipulate:
     

    include: lostfilm.yml
```
